// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace democrud.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230803051816_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("aspnetserver.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Age = 1,
                            FirstName = "Demo",
                            LastName = "Name1",
                            MobileNo = "1234567891"
                        },
                        new
                        {
                            PostId = 2,
                            Age = 2,
                            FirstName = "Demo",
                            LastName = "Name2",
                            MobileNo = "1234567892"
                        },
                        new
                        {
                            PostId = 3,
                            Age = 3,
                            FirstName = "Demo",
                            LastName = "Name3",
                            MobileNo = "1234567893"
                        },
                        new
                        {
                            PostId = 4,
                            Age = 4,
                            FirstName = "Demo",
                            LastName = "Name4",
                            MobileNo = "1234567894"
                        },
                        new
                        {
                            PostId = 5,
                            Age = 5,
                            FirstName = "Demo",
                            LastName = "Name5",
                            MobileNo = "1234567895"
                        },
                        new
                        {
                            PostId = 6,
                            Age = 6,
                            FirstName = "Demo",
                            LastName = "Name6",
                            MobileNo = "1234567896"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
